export const teaminfo = [
  {
    id: 1,
    name: "Jonathan Debella",
    username: "Joniye",
    email: "jonathandebella00@gmail.com",
    image: "/teamImages/jonathan.jpg",
    role: "Full Stack",
    bio: "I am a third year student at the University of Texas at Austin. I like to read manga in my downtime.",
    commits: 0,
    issues: 0,
    tests: 0,
  },
  {
    id: 2,
    name: "Dani Amir",
    username: "daniamir",
    email: "daniamir@utexas.edu",
    image: "/teamImages/dani.jpeg",
    role: "Full Stack, Phase 2 Leader",
    bio: "I'm a junior at the University of Texas at Austin. I love playing video games and making them.",
    commits: 0,
    issues: 0,
    tests: 15,
  },
  {
    id: 3,
    name: "Ruchi Bhalani",
    username: "r-bhalani",
    email: "ruchi.bhalani@utexas.edu",
    image: "/teamImages/ruchi.png",
    role: "Full Stack, Phase 4 Leader ",
    bio: "I'm a second year CS major at UT Austin! I'm from Plano, Texas and in my free time I like biking, watching true crime shows, and reading poetry.",
    commits: 0,
    issues: 0,
    tests: 61,
  },
  {
    id: 4,
    name: "Anthony Modica",
    username: "anthony.modica",
    email: "modica.c.anthony@gmail.com",
    image: "/teamImages/anthony.jfif",
    role: "Full Stack, Phase 1 Leader",
    bio: "I'm a sophomore CS major here at UT, and I also grew up here in Austin, TX! In my free time I enjoy playing video games and weightlifting.",
    commits: 0,
    issues: 0,
    tests: 0,
  },
  {
    id: 5,
    name: "Martin Nguyen",
    username: "martn-nguyen",
    email: "martinmnguyen@utexas.edu",
    image: "/teamImages/martin.jpg",
    role: "Full Stack, Phase 3 Leader",
    bio: "I'm a third year computer science major minoring in business at UT Austin! In my free time, I like to watch Twitch streams and play video games.",
    commits: 0,
    issues: 0,
    tests: 0,
  },
];
