export default {
  currencies: [
    "Afghan Afghani",
    "Algerian Dinar",
    "Argentine Peso",
    "Armenian Dram",
    "Aruban Florin",
    "Australian Dollar",
    "Azerbaijan Manat",
    "Bahamian Dollar",
    "Bahraini Dinar",
    "Thai Baht",
    "Panamanian Balboa",
    "Barbados Dollar",
    "Belarusian Ruble",
    "Belize Dollar",
    "Bermudian Dollar",
    "Bolivian Boliviano",
    "Venezuelan bolívar",
    "Brazilian Real",
    "Brunei Dollar",
    "Bulgarian Lev",
    "Burundi Franc",
    "West African CFA franc",
    "Central African CFA franc",
    "CFP Franc",
    "Cape Verdean Escudo",
    "Canadian Dollar",
    "Cayman Islands Dollar",
    "Chilean Peso",
    "Colombian Peso",
    "Comorian Franc ",
    "Congolese Franc",
    "Convertible Mark",
    "Nicaraguan Córdoba",
    "Costa Rican Colon",
    "Cuban Peso",
    "Czech Koruna",
    "Gambian Dalasi",
    "Danish Krone",
    "Macedonian Denar",
    "Djibouti Franc",
    "São Tomé and Príncipe dobra",
    "Dominican Peso",
    "Vietnamese Dong",
    "East Caribbean Dollar",
    "Egyptian Pound",
    "Ethiopian Birr",
    "Euro",
    "Falkland Islands Pound",
    "Fiji Dollar",
    "Hungarian Forint",
    "Ghana Cedi",
    "Gibraltar Pound",
    "Haitian Gourde",
    "Paraguayan Guarani",
    "Guinean Franc",
    "Guyana Dollar",
    "Hong Kong Dollar",
    "Ukrainian Hryvnia",
    "Iceland Krona",
    "Indian Rupee",
    "Iranian Rial",
    "Iraqi Dinar",
    "Jamaican Dollar",
    "Jordanian Dinar",
    "Kenyan Shilling",
    "Papua New Guinean Kina",
    "Croatian Kuna",
    "Kuwaiti Dinar",
    "Angolan Kwanza",
    "Myanmar Kyat",
    "Lao Kip",
    "Georgian Lari",
    "Lebanese Pound",
    "Albanian Lek",
    "Honduran Lempira",
    "Sierra Leonean Leone",
    "Liberian Dollar",
    "Libyan Dinar",
    "Swazi Lilangeni",
    "Lesotho loti",
    "Malagasy Ariary",
    "Malawi Kwacha",
    "Malaysian Ringgit",
    "Mauritius Rupee",
    "Mexican Peso",
    "Moldovan Leu",
    "Moroccan Dirham",
    "Mozambique Metical",
    "Nigerian Naira",
    "Eritrean nakfa",
    "Namibia Dollar",
    "Nepalese Rupee",
    "Netherlands Antillean Guilder",
    "New Israeli Sheqel",
    "New Taiwan Dollar",
    "New Zealand Dollar",
    "Bhutanese Ngultrum",
    "North Korean Won",
    "Norwegian Krone",
    "Mauritanian Ouguiya",
    "Pakistan Rupee",
    "Macanese Pataca",
    "Tongan Paʻanga",
    "Cuban Convertible Peso",
    "Uruguayan Peso",
    "Philippine Peso",
    "Pound Sterling",
    "Botswanan Pula",
    "Qatari Rial",
    "Guatemalan quetzal",
    "South African Rand",
    "Rial Omani",
    "Cambodian riel",
    "Romanian Leu",
    "Maldivian Rufiyaa",
    "Indonesian Rupiah",
    "Russian Ruble",
    "Rwanda Franc",
    "Saint Helena Pound",
    "Saudi Riyal",
    "Serbian Dinar",
    "Seychelles Rupee",
    "Singapore Dollar",
    "Peruvian sol",
    "Solomon Islands Dollar",
    "Kyrgystani Som",
    "Somali Shilling",
    "Tajikistani Somoni",
    "South Sudanese Pound",
    "Sri Lanka Rupee",
    "Sudanese Pound",
    "Surinam Dollar",
    "Swedish Krona",
    "Swiss Franc",
    "Syrian Pound",
    "Bangladeshi Taka",
    "Samoan tālā",
    "Tanzanian Shilling",
    "Kazakhstani",
    "Trinidad and Tobago Dollar",
    "Mongolian tögrög",
    "Tunisian Dinar",
    "Turkish Lira",
    "Turkmenistan New Manat",
    "UAE Dirham",
    "US Dollar",
    "Uganda Shilling",
    "Uzbekistan Sum",
    "Vanuatu vatu",
    "South Korean won",
    "Yemeni Rial",
    "Japanese Yen",
    "Yuan Renminbi",
    "Zambian Kwacha",
    "Zimbabwe Dollar",
    "Polish Złoty",
  ],
  languages: [
    "Afrikaans",
    "Amharic",
    "Arabic",
    "Aymara",
    "Azerbaijani",
    "Belarusian",
    "Bengali",
    "Berber languages",
    "Bislama",
    "Bokmål",
    "Norwegian",
    "Bosnian",
    "Bulgarian",
    "Catalan",
    "Valencian",
    "Central Khmer",
    "Chamorro",
    "Chichewa",
    "Croatian",
    "Danish",
    "Maldivian",
    "Dzongkha",
    "English",
    "Estonian",
    "Faroese",
    "Fijian",
    "Filipino",
    "Finnish",
    "Gilbertese",
    "Guarani",
    "Haitian Creole",
    "Hebrew",
    "Herero",
    "Hindi",
    "Hiri Motu",
    "Hungarian",
    "Indonesian",
    "Irish",
    "Italian",
    "Japanese",
    "Greenlandic",
    "Kazakh",
    "Khoisan languages",
    "Kinyarwanda",
    "Kyrgyz",
    "Kongo",
    "Korean",
    "Lao",
    "Latin",
    "Latvian",
    "Lingala",
    "Lithuanian",
    "Lozi",
    "Luba-Lulua",
    "Luxembourgish",
    "Malagasy",
    "Maltese",
    "Manx",
    "Marshallese",
    "Mongolian",
    "Montenegrin",
    "Nauru",
    "North Ndebele",
    "South Ndebele",
    "Ndonga",
    "Nepali",
    "Niuean",
    "Norwegian",
    "Nynorsk",
    "Imperial Aramaic",
    "Palauan",
    "Papiamento",
    "Polish",
    "Portuguese",
    "Pashto",
    "Quechua",
    "Cook Islands Maori",
    "Romansh",
    "Rundi",
    "Russian",
    "Sami languages",
    "Samoan",
    "Sango",
    "Serbian",
    "Shona",
    "Sinhalese",
    "Slovenian",
    "Somali",
    "Sotho",
    "Spanish",
    "Swahili",
    "Swati",
    "Swedish",
    "Swiss German",
    "Tajik",
    "Tamil",
    "Tetum",
    "Thai",
    "Tigrinya",
    "Tok Pisin",
    "Tokelau",
    "Tongan",
    "Tsonga",
    "Tswana",
    "Turkish",
    "Turkmen",
    "Tuvalu",
    "Ukrainian",
    "Urdu",
    "Uzbek",
    "Venda",
    "Vietnamese",
    "Xhosa",
    "Zulu",
  ],
  region: ["Africa", "Americas", "Antarctic", "Asia", "Europe", "Oceania"],
  subregion: [
    "Australia and New Zealand",
    "Caribbean",
    "Central America",
    "Central Asia",
    "Central Europe",
    "Eastern Africa",
    "Eastern Asia",
    "Eastern Europe",
    "Melanesia",
    "Micronesia",
    "Middle Africa",
    "North America",
    "Northern Africa",
    "Northern Europe",
    "Polynesia",
    "South America",
    "South-Eastern Asia",
    "Southeast Europe",
    "Southern Africa",
    "Southern Asia",
    "Southern Europe",
    "Western Africa",
    "Western Asia",
    "Western Europe",
  ],
};
